export const data = [
  {
    id: 1,
    label: "ResumeRefine",
    imgSrc: "/assets/projects/ResumeRefine.png",
    desc: "RAG pipeline to evaluate resumes against job descriptions using embedding-based semantic similarity. Generates rewrite suggestions, detects skill gaps, and creates contextual interview questions.",
    tags: ["Python", "LangChain", "FAISS", "HuggingFace"],
    view: "https://thesawankumar-resumerefine-app-g2j2q2.streamlit.app/",
    github: "https://github.com/thesawankumar",
    featured: true,
  },
  {
    id: 2,
    label: "SnapBuy",
    imgSrc: "/assets/projects/SnapBuy.png",
    desc: "Full-stack e-commerce platform (Customer, Seller, Admin) with secure OTP auth, Razorpay integration, seller dashboard, wishlist, cart, and order tracking.",
    tags: ["React", "Spring Boot", "MongoDB", "Razorpay", "Docker"],
    view: "https://moonlit-malabi-c3f48e.netlify.app",
    github: "https://github.com/thesawankumar",
    featured: false,
  },
  {
    id: 3,
    label: "NoteSphere",
    imgSrc: "/assets/projects/notion-clone.png",
    desc: "Full-stack note-taking app with real-time data sync, optimized queries, advanced search, and cross-platform optimization — boosted mobile engagement by 50%.",
    tags: ["Next.js", "Convex", "Tailwind CSS"],
    view: "https://notion-clone-sawan1k.vercel.app",
    github: "https://github.com/thesawankumar",
    featured: false,
  },
  {
    id: 4,
    label: "ImagineX",
    imgSrc: "/assets/projects/ImagineX.png",
    desc: "Full-stack MERN app integrating ClipDrop API for AI-powered text-to-image generation with credit system and image download features.",
    tags: ["React", "Node.js", "MongoDB", "ClipDrop API"],
    view: "https://unique-faloodeh-546146.netlify.app/",
    github: "https://github.com/thesawankumar",
    featured: false,
  },
  {
    id: 5,
    label: "Castlewood Gym",
    imgSrc: "/assets/projects/castlewood-gym.png",
    desc: "Freelance project — modern gym & fitness website with membership plans, trainer profiles, class schedule, and WhatsApp contact integration.",
    tags: ["React", "Tailwind CSS", "Netlify"],
    view: "https://mellifluous-smakager-51b669.netlify.app",
    github: "https://github.com/thesawankumar",
    featured: false,
    freelance: true,
  },
];
